// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./dbTypes";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable()
);

export const questionsRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string().nullable(),
  id: z.number(),
  question: z.string().nullable(),
});

export const questionsInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.number().optional(),
  question: z.string().optional().nullable(),
});

export const questionsUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.number().optional(),
  question: z.string().optional().nullable(),
});

export const questionsTagsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  question_id: z.number().nullable(),
  tag_id: z.number().nullable(),
});

export const questionsTagsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  question_id: z.number().optional().nullable(),
  tag_id: z.number().optional().nullable(),
});

export const questionsTagsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  question_id: z.number().optional().nullable(),
  tag_id: z.number().optional().nullable(),
});

export const rolesRowSchema = z.object({
  company: z.string(),
  created_at: z.string(),
  current: z.boolean().nullable(),
  endMonth: z.string().nullable(),
  id: z.number(),
  startMonth: z.string(),
  title: z.string(),
  user_id: z.string(),
});

export const rolesInsertSchema = z.object({
  company: z.string(),
  created_at: z.string().optional(),
  current: z.boolean().optional().nullable(),
  endMonth: z.string().optional().nullable(),
  id: z.number().optional(),
  startMonth: z.string(),
  title: z.string(),
  user_id: z.string(),
});

export const rolesUpdateSchema = z.object({
  company: z.string().optional(),
  created_at: z.string().optional(),
  current: z.boolean().optional().nullable(),
  endMonth: z.string().optional().nullable(),
  id: z.number().optional(),
  startMonth: z.string().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const storiesRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  role_id: z.number().nullable(),
  text: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const storiesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  role_id: z.number().optional().nullable(),
  text: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const storiesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  role_id: z.number().optional().nullable(),
  text: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const storiesBulletpointsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  order: z.number().nullable(),
  story_id: z.number().nullable(),
  text: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const storiesBulletpointsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  order: z.number().optional().nullable(),
  story_id: z.number().optional().nullable(),
  text: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const storiesBulletpointsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  order: z.number().optional().nullable(),
  story_id: z.number().optional().nullable(),
  text: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const storiesTagsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  story_id: z.number(),
  tag_id: z.number(),
});

export const storiesTagsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  story_id: z.number(),
  tag_id: z.number(),
});

export const storiesTagsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  story_id: z.number().optional(),
  tag_id: z.number().optional(),
});

export const tagsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  name: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const tagsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const tagsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});
